apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-custom-error-page-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      misoboy-service: app-custom-error-page
  template:
    metadata:
      labels:
        misoboy-service: app-custom-error-page
    spec:
      containers:
      - name: app-custom-error-page
        image: docker.pkg.github.com/misoboy/k8s-ingress-custom-error-page/ingress-custom-error-page:1.0.38
        ports:
        - protocol: TCP
          containerPort: 8080
      imagePullSecrets:
        - name: regcred